### 장바구니에 상품을 추가하는 메서드 입니다.
POST http://localhost:8080/carts HTTP/1.1
Content-Type: application/json

{
  "cartId": "1",
  "productId": 20,
  "carePeriod": 3,
  "quantity": 13
}
### 장바구니에 담긴 상품의 수량을 변경하는 메서드 입니다.
PUT http://localhost:8080/carts/1/products/1 HTTP/1.1
Content-Type: application/json

{
  "cartId": "2",
  "productId": 14,
  "carePeriod": 3,
  "quantity": 16
}
### 장바구니에 담긴 상품의 수량을 +1하는 메서드 입니다.
PUT http://localhost:8080/carts/1/products/1/increase HTTP/1.1
Content-Type: application/json

{
  "cartId": "2",
  "productId": 14,
  "carePeriod": 3
}
### 장바구니에 담긴 상품의 수량을 -1하는 메서드 입니다.
PUT http://localhost:8080/carts/1/products/1/decrease HTTP/1.1
Content-Type: application/json

{
  "cartId": "2",
  "productId": 14,
  "carePeriod": 3
}
### 장바구니에 담긴 상품을 삭제하는 메서드 입니다.
DELETE http://localhost:8080/carts/1/products/1 HTTP/1.1
Content-Type: application/json

{
  "cartId": "2",
  "productId": 14,
  "carePeriod": 3
}
###
POST http://localhost:8080/carts/1 HTTP/1.1